version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
